# Generated by Django 4.1.2 on 2022-12-18 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_weeklytasks_weeklytask'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytask',
            name='date_time',
            field=models.DateTimeField(default=None),
        ),
    ]
