# Generated by Django 4.1.2 on 2022-12-18 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_weeklytask_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklytask',
            name='color',
            field=models.CharField(default='3a9703', max_length=16),
        ),
    ]
