# Generated by Django 4.1.4 on 2022-12-22 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_weeklytask_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklytask',
            name='color',
            field=models.CharField(default='#608376', max_length=16),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='taskname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
