# Generated by Django 4.1.4 on 2022-12-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_weeklytask_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklytask',
            name='color',
            field=models.CharField(default='#64d14a', max_length=16),
        ),
    ]
