# Generated by Django 4.1.4 on 2022-12-23 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_alter_weeklytask_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferredMode',
            field=models.CharField(default='Week Mode', max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='color',
            field=models.CharField(default='#e63510', max_length=16),
        ),
    ]
