# Generated by Django 4.1.4 on 2022-12-25 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_weeklytask_color_uploadimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklytask',
            name='color',
            field=models.CharField(default='#128f36', max_length=16),
        ),
    ]
