# Generated by Django 4.1.4 on 2022-12-25 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_uploadimage_image_alter_weeklytask_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default=0, upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='color',
            field=models.CharField(default='#12d2cc', max_length=16),
        ),
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
