# Generated by Django 4.1.4 on 2022-12-25 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_userimage_remove_user_image_alter_weeklytask_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='userimage',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='weeklytask',
            name='color',
            field=models.CharField(default='#a63fcd', max_length=16),
        ),
    ]
