# Generated by Django 4.1.4 on 2022-12-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_userimage_user_id_alter_weeklytask_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklytask',
            name='color',
            field=models.CharField(default='#5e850c', max_length=16),
        ),
    ]
