# Generated by Django 4.1.4 on 2022-12-27 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_userimage_image_alter_weeklytask_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklytask',
            name='color',
            field=models.CharField(default='FFFFFF', max_length=16),
        ),
    ]
