# Generated by Django 4.1.4 on 2022-12-28 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_alter_weeklytask_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userimage',
            name='image',
            field=models.ImageField(default='media/images/default.jpg', upload_to='images/'),
        ),
    ]
